/*
 Navicat Premium Dump SQL

 Source Server         : Localhost
 Source Server Type    : MySQL
 Source Server Version : 80030 (8.0.30)
 Source Host           : localhost:3306
 Source Schema         : staging

 Target Server Type    : MySQL
 Target Server Version : 80030 (8.0.30)
 File Encoding         : 65001

 Date: 08/11/2025 18:24:05
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for staging.rawtgdd
-- ----------------------------
DROP TABLE IF EXISTS `staging.rawtgdd`;
CREATE TABLE `staging.rawtgdd`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `Tên sản phẩm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Giá` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Source` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Hệ điều hành:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Chip xử lý (CPU):` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Tốc độ CPU:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Chip đồ họa (GPU):` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `RAM:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Dung lượng lưu trữ:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Dung lượng còn lại (khả dụng) khoảng:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Danh bạ:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Độ phân giải camera sau:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Quay phim camera sau:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Đèn Flash camera sau:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Tính năng camera sau:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Độ phân giải camera trước:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Tính năng camera trước:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Công nghệ màn hình:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Độ phân giải màn hình:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Màn hình rộng:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Độ sáng tối đa:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Mặt kính cảm ứng:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Dung lượng pin:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Loại pin:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Hỗ trợ sạc tối đa:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Công nghệ pin:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Bảo mật nâng cao:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Tính năng đặc biệt:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Kháng nước, bụi:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Ghi âm:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Xem phim:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Nghe nhạc:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Mạng di động:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `SIM:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Wifi:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `GPS:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Bluetooth:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Cổng kết nối/sạc:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Jack tai nghe:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Kết nối khác:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Thiết kế:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Chất liệu:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Kích thước, khối lượng:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Thời điểm ra mắt:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `Hãng:` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `created_at` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `source_file` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 8 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of staging.rawtgdd
-- ----------------------------
INSERT INTO `staging.rawtgdd` VALUES (1, 'iPhone 16 Pro Max 256GB', '30590000', 'https://www.thegioididong.com/dtdd/iphone-16-pro-max', 'iOS 18', 'Apple A18 Pro 6 nhân', 'Hãng không công bố', 'Apple GPU 6 nhân', '8 GB', '256 GB', '241 GB', 'Không giới hạn', 'Chính 48 MP & Phụ 48 MP, 12 MP', 'HD 720p@30fps | FullHD 1080p@60fps | FullHD 1080p@30fps | FullHD 1080p@25fps | FullHD 1080p@240fps | FullHD 1080p@120fps | 4K 2160p@60fps | 4K 2160p@30fps | 4K 2160p@25fps | 4K 2160p@24fps | 4K 2160p@120fps | 4K 2160p@100fps | 2.8K 60fps', 'Có', 'Ảnh Raw | Điều khiển camera (Camera Control) | Zoom quang học | Zoom kỹ thuật số | Xóa phông | Trôi nhanh thời gian (Time Lapse) | Smart HDR 5 | Siêu độ phân giải | Siêu cận (Macro) | Quay video định dạng Log | Quay video ProRes | Quay chậm (Slow Motion) | Live Photos | Góc siêu rộng (Ultrawide) | Dolby Vision HDR | Deep Fusion | Cinematic | Chụp ảnh liên tục | Chống rung quang học (OIS) | Chân dung đêm | Bộ lọc màu | Ban đêm (Night Mode) | Chế độ hành động (Action Mode) | Photonic Engine', '12 MP', 'Smart HDR 5 | Xóa phông | Trôi nhanh thời gian (Time Lapse) | Retina Flash | Quay video định dạng Log | Quay video ProRes | Quay video Full HD | Quay video 4K | Quay chậm (Slow Motion) | Live Photos | Deep Fusion | Chụp ảnh liên tục | Chụp ảnh Raw | Chụp đêm | Chống rung | Cinematic | Bộ lọc màu | Photonic Engine', 'OLED', 'Super Retina XDR (1320 x 2868 Pixels)', '6.9\" - Tần số quét120 Hz | 120 Hz', '2000 nits', 'Kính cường lực Ceramic Shield', '33 giờ', 'Li-Ion', '20 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc ngược qua cáp | Sạc không dây MagSafe | Sạc không dây', 'Mở khoá khuôn mặt Face ID', 'Âm thanh Dolby Atmos | Phát hiện va chạm (Crash Detection) | Màn hình luôn hiển thị AOD | HDR10+ | HDR10 | DCI-P3 | Công nghệ âm thanh Dolby Digital Plus | Công nghệ hình ảnh Dolby Vision | Công nghệ HLG | Công nghê âm thanh Dolby Digital | Chạm 2 lần sáng màn hình | Apple Pay | Loa kép', 'IP68', 'Ghi âm mặc định', 'MP4 | HEVC', 'MP3 | FLAC | Apple Lossless | APAC | AAC', 'Hỗ trợ 5G', '1 Nano SIM & 1 eSIM', 'Wi-Fi MIMO | Wi-Fi 7', 'iBeacon | QZSS | NavIC | GPS | GLONASS | GALILEO | BEIDOU', 'v5.3', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung Titan & Mặt lưng kính cường lực', 'Dài 163 mm - Ngang 77.6 mm - Dày 8.25 mm - Nặng 227 g', '09/2024', 'iPhone (Apple).Xem thông tin hãng | Xem thông tin hãng', '2025-10-26 20:36:31', 'tgdd_products_2025_10_26_20_36_31.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (2, 'iPhone 17 Pro 256GB', '34990000', 'https://www.thegioididong.com/dtdd/iphone-17-pro', 'iOS 26', 'Apple A19 Pro 6 nhân', 'Hãng không công bố', 'Apple GPU 6 nhân', '12 GB', '256 GB', '241 GB', 'Không giới hạn', 'Chính 48 MP & Phụ 48 MP, 48 MP', 'HD 720p@30fps | FullHD 1080p@60fps | FullHD 1080p@30fps | FullHD 1080p@25fps | FullHD 1080p@120fps | 4K 2160p@60fps | 4K 2160p@30fps | 4K 2160p@25fps | 4K 2160p@24fps | 4K 2160p@120fps | 4K 2160p@100fps | 2.8K 60fps', 'Có', 'Ảnh Raw | Điều khiển camera (Camera Control) | Điều chỉnh khẩu độ | Zoom quang học | Zoom kỹ thuật số | Xóa phông | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Toàn cảnh (Panorama) | Smart HDR 5 | Siêu độ phân giải | Siêu cận (Macro) | Quay video định dạng Log | Quay video hiển thị kép | Quay video ProRes | Quay chậm (Slow Motion) | Live Photos | Gắn thẻ địa lý (Geotagging) | Góc siêu rộng (Ultrawide) | Dolby Vision HDR | Deep Fusion | Cinematic | Chụp ảnh liên tục | Chống rung điện tử kỹ thuật số (EIS) | Chống rung quang học (OIS) | Ban đêm (Night Mode) | Chế độ hành động (Action Mode) | Photonic Engine', '18 MP', 'Smart HDR 5 | Xóa phông | Video hiển thị kép | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Retina Flash | Quay video HD | Quay video Full HD | Quay video 4K | Quay chậm (Slow Motion) | Nhãn dán (AR Stickers) | Live Photos | Deep Fusion | Chụp ảnh Raw | Chụp đêm | Chống rung điện tử kỹ thuật số (EIS) | Cinematic | TrueDepth | Photonic Engine', 'OLED', 'Super Retina XDR (1206 x 2622 Pixels)', '6.3\" - Tần số quét120 Hz | 120 Hz', '3000 nits', 'Kính cường lực Ceramic Shield 2', '31 giờ', 'Li-Ion', '40 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc ngược qua cáp | Sạc không dây MagSafe | Sạc không dây', 'Mở khoá khuôn mặt Face ID', 'Âm thanh Dolby Atmos | Xoá vật thể AI | Viết AI | Trung tâm màn hình (Center Stage) | Phát hiện va chạm (Crash Detection) | Màn hình luôn hiển thị AOD | Khoanh tròn để tìm kiếm | HDR10+ | HDR10 | DCI-P3 | Công nghệ âm thanh Dolby Digital Plus | Công nghệ True Tone | Công nghệ HLG | Công nghê âm thanh Dolby Digital | Chạm 2 lần sáng màn hình | Apple Pay | Loa kép', 'IP68', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'MP4 | AV1 | HEVC', 'MP3 | FLAC | Apple Lossless | APAC | AAC', 'Hỗ trợ 5G', '1 Nano SIM & 1 eSIM', 'Wi-Fi MIMO | Wi-Fi 7', 'iBeacon | QZSS | NavIC | GPS | GLONASS | GALILEO | BEIDOU', 'v6.0', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung nhôm nguyên khối & Mặt lưng kính cường lực', 'Dài 150 mm - Ngang 71.9 mm - Dày 8.75 mm - Nặng 204 g', '09/2025', 'iPhone (Apple).Xem thông tin hãng | Xem thông tin hãng', '2025-10-26 20:40:47', 'tgdd_products_2025_10_26_20_40_47.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (3, 'iPhone Air 256GB', '31490000', 'https://www.thegioididong.com/dtdd/iphone-air', 'iOS 26', 'Apple A19 Pro 6 nhân', 'Hãng không công bố', 'Apple GPU 5 nhân', '12 GB', '256 GB', '241 GB', 'Hãng không công bố', '48 MP', 'HD 720p@30fps | FullHD 1080p@60fps | FullHD 1080p@30fps | FullHD 1080p@25fps | FullHD 1080p@240fps | FullHD 1080p@120fps | 4K 2160p@60fps | 4K 2160p@30fps | 4K 2160p@25fps | 4K 2160p@24fps | 2.8K 60fps', 'Có', 'Điều khiển camera (Camera Control) | Điều chỉnh khẩu độ | Zoom quang học | Zoom kỹ thuật số | Xóa phông | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Toàn cảnh (Panorama) | Smart HDR 5 | Siêu độ phân giải | Quay video hiển thị kép | Quay chậm (Slow Motion) | Live Photos | Gắn thẻ địa lý (Geotagging) | Deep Fusion | Chụp ảnh liên tục | Chống rung quang học (OIS) | Chế độ hành động (Action Mode) | Ban đêm (Night Mode) | Photonic Engine', '18 MP', 'Smart HDR 5 | Điều chỉnh khẩu độ | Xóa phông | Video hiển thị kép | Trôi nhanh thời gian (Time Lapse) | Retina Flash | Quay video HD | Quay video Full HD | Quay video 4K | Quay chậm (Slow Motion) | Nhãn dán (AR Stickers) | Live Photos | Deep Fusion | Chụp ảnh liên tục | Chụp đêm | Chống rung điện tử kỹ thuật số (EIS) | TrueDepth | Photonic Engine', 'OLED', 'Super Retina XDR (1260 x 2736 Pixels)', '6.5\" - Tần số quét120 Hz | 120 Hz', '3000 nits', 'Kính cường lực Ceramic Shield 2', '27 giờ', 'Li-Ion', '20 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc không dây MagSafe | Sạc không dây', 'Mở khoá khuôn mặt Face ID', 'Âm thanh Dolby Atmos | Xoá vật thể AI | Viết AI | Trung tâm màn hình (Center Stage) | Phát hiện va chạm (Crash Detection) | Màn hình luôn hiển thị AOD | Loa kép | Khoanh tròn để tìm kiếm | HDR10+ | HDR10 | DCI-P3 | Công nghệ âm thanh Dolby Digital Plus | Công nghệ True Tone | Công nghệ hình ảnh Dolby Vision | Công nghệ HLG | Công nghê âm thanh Dolby Digital | Chạm 2 lần sáng màn hình', 'IP68', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'MP4 | AV1 | HEVC', 'MP3 | FLAC | Apple Lossless | APAC | AAC', 'Hỗ trợ 5G', '2 eSIM (hoạt động cùng lúc)', 'Wi-Fi MIMO | Wi-Fi 7', 'iBeacon | QZSS | NavIC | GPS | GLONASS | GALILEO | BEIDOU', 'v6.0', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung Titan & Mặt lưng kính cường lực', 'Dài 156.2 mm - Ngang 74.7 mm - Dày 5.64 mm - Nặng 165 g', '09/2025', 'iPhone (Apple).Xem thông tin hãng | Xem thông tin hãng', '2025-10-26 20:40:47', 'tgdd_products_2025_10_26_20_40_47.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (4, 'iPhone 17 256GB', '24990000', 'https://www.thegioididong.com/dtdd/iphone-17', 'iOS 26', 'Apple A19 6 nhân', 'Hãng không công bố', 'Apple GPU 5 nhân', '8 GB', '256 GB', '241 GB', 'Không giới hạn', 'Chính 48 MP & Phụ 48 MP', 'HD 720p@30fps | FullHD 1080p@60fps | FullHD 1080p@30fps | FullHD 1080p@25fps | FullHD 1080p@240fps | FullHD 1080p@120fps | 4K 2160p@60fps | 4K 2160p@30fps | 4K 2160p@25fps | 4K 2160p@24fps | 2.8K 60fps', 'Có', 'Điều khiển camera (Camera Control) | Điều chỉnh khẩu độ | Zoom quang học | Zoom kỹ thuật số | Xóa phông | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Smart HDR 5 | Siêu độ phân giải | Siêu cận (Macro) | Quay video hiển thị kép | Quay chậm (Slow Motion) | Live Photos | Gắn thẻ địa lý (Geotagging) | Góc siêu rộng (Ultrawide) | Dolby Vision HDR | Deep Fusion | Cinematic | Chụp ảnh liên tục | Chống rung điện tử kỹ thuật số (EIS) | Chống rung quang học (OIS) | Chế độ hành động (Action Mode) | Ban đêm (Night Mode) | Photonic Engine', '18 MP', 'Smart HDR 5 | Xóa phông | Video hiển thị kép | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Retina Flash | Quay video HD | Quay video Full HD | Quay video 4K | Quay chậm (Slow Motion) | Nhãn dán (AR Stickers) | Live Photos | Deep Fusion | Cinematic | Chụp ảnh liên tục | Chụp đêm | Chống rung điện tử kỹ thuật số (EIS) | TrueDepth | Photonic Engine', 'OLED', 'Super Retina XDR (1206 x 2622 Pixels)', '6.3\" - Tần số quét120 Hz | 120 Hz', '3000 nits', 'Kính cường lực Ceramic Shield 2', '30 giờ', 'Li-Ion', '40 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc ngược qua cáp | Sạc không dây MagSafe | Sạc không dây', 'Mở khoá khuôn mặt Face ID', 'Âm thanh Dolby Atmos | Xoá vật thể AI | Viết AI | Trung tâm màn hình (Center Stage) | Phát hiện va chạm (Crash Detection) | Màn hình luôn hiển thị AOD | Khoanh tròn để tìm kiếm | HDR10+ | HDR10 | DCI-P3 | Công nghệ âm thanh Dolby Digital Plus | Công nghệ True Tone | Công nghệ HLG | Công nghê âm thanh Dolby Digital | Chạm 2 lần sáng màn hình | Apple Pay | Loa kép', 'IP68', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'MP4 | AV1 | HEVC', 'MP3 | FLAC | Apple Lossless | APAC | AAC', 'Hỗ trợ 5G', '1 Nano SIM & 1 eSIM', 'Wi-Fi MIMO | Wi-Fi 7', 'iBeacon | QZSS | NavIC | GPS | GLONASS | GALILEO | BEIDOU', 'v6.0', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung nhôm & Mặt lưng kính cường lực', 'Dài 149.6 mm - Ngang 71.5 mm - Dày 7.95 mm - Nặng 177 g', '09/2025', 'iPhone (Apple).Xem thông tin hãng | Xem thông tin hãng', '2025-10-26 20:40:47', 'tgdd_products_2025_10_26_20_40_47.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (5, 'Samsung Galaxy S25 FE 5G 8GB/128GB', '14390000', 'https://www.thegioididong.com/dtdd/samsung-galaxy-s25-fe-5g-8gb-128gb', 'Android 16', 'Exynos 2400 10 nhân', '3.2 GHz', 'Đang cập nhật', '8 GB', '128 GB', '104 GB', 'Không giới hạn', 'Chính 50 MP & Phụ 12 MP, 8 MP', '8K 4320p@30fps', 'Có', 'Zoom quang học | Zoom kỹ thuật số | Toàn cảnh (Panorama) | Super HDR | Góc siêu rộng (Ultrawide) | Chọn ảnh chân dung đẹp nhất (Best Face) | Ban đêm (Night Mode)', '12 MP', 'Chọn ảnh chân dung đẹp nhất (Best Face)', 'Dynamic AMOLED 2X', 'Full HD+ (1080 x 2340 Pixels)', '6.7\" - Tần số quét120 Hz | 120 Hz', '1900 nits', 'Kính cường lực Corning Gorilla Glass Victus+', '4900 mAh', 'Đang cập nhật', '45 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc không dây', 'Mở khoá vân tay dưới màn hình | Mở khoá khuôn mặt', 'Trợ lý ảo Google Gemini | Now Brief | Khoanh tròn để tìm kiếm | Audio Eraser', 'IP68', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'WEBM | MP4 | MKV | M4V | FLV | AVI | 3GP | 3G2', 'DFF | XMF | WAV | RTX | RTTTL | OTA | OGG | OGA | Midi | MXMF | MP3 | M4A | IMY | FLAC | DSF | AWB | APE | AMR | AAC | 3GA', 'Hỗ trợ 5G', '2 Nano SIM + 1 eSIM', 'Có', 'Có', 'Có', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung nhôm & Mặt lưng kính cường lực', 'Dài 161.3 mm - Ngang 76.6 mm - Dày 7.4 mm - Nặng 190 g', '09/2025', 'Samsung.Xem thông tin hãng | Xem thông tin hãng', '2025-10-26 20:40:47', 'tgdd_products_2025_10_26_20_40_47.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (6, 'Samsung Galaxy A17 5G 8GB/128GB', '5990000', 'https://www.thegioididong.com/dtdd/samsung-galaxy-a17-5g-8gb-128gb', 'Android 15', 'Exynos 1330', '2 nhân 2.4 GHz & 6 nhân 2 GHz', 'Đang cập nhật', '8 GB', '128 GB', '107 GB', 'Không giới hạn', 'Chính 50 MP & Phụ 5 MP, 2 MP', 'HD 720p@120fps | FullHD 1080p@30fps', 'Có', 'Zoom kỹ thuật số | Xóa phông | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Toàn cảnh (Panorama) | Siêu cận (Macro) | Quay chậm (Slow Motion) | Làm đẹp | Chống rung quang học (OIS) | Chế độ thức ăn | Chuyên nghiệp (Pro) | Ban đêm (Night Mode)', '13 MP', 'Xóa phông | Nhãn dán (AR Stickers) | Làm đẹp', 'Super AMOLED', 'Full HD+ (1080 x 2340 Pixels)', '6.7\" - Tần số quét 90 Hz', '800 nits', 'Kính cường lực Corning Gorilla Glass Victus', '5000 mAh', 'Li-Ion', '25 W', 'Tiết kiệm pin | Sạc pin nhanh', 'Mở khoá vân tay cạnh viền | Mở khoá khuôn mặt', 'Trợ lý ảo Google Gemini | Smart Switch (ứng dụng chuyển đổi dữ liệu) | Khoanh tròn để tìm kiếm', 'IP54', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'WEBM | MP4 | MKV | M4V | FLV | AVI | 3GP | 3G2', 'XMF | WAV | RTX | RTTTL | OTA | OGG | OGA | Midi | MXMF | MP3 | M4A | IMY | FLAC | AWB | AMR | AAC | 3GA', 'Hỗ trợ 5G', '2 Nano SIM', 'Wi-Fi hotspot | Wi-Fi Direct | Wi-Fi 5 | Dual-band (2.4 GHz/5 GHz)', 'QZSS | GPS | GLONASS | GALILEO | BEIDOU', 'v5.3', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung & Mặt lưng nhựa', 'Dài 164.4 mm - Ngang 77.9 mm - Dày 7.5 mm - Nặng 192 g', '08/2025', 'Samsung.Xem thông tin hãng | Xem thông tin hãng', '2025-11-04 21:51:37', 'tgdd_products_2025_11_04_21_51_36.xlsx');
INSERT INTO `staging.rawtgdd` VALUES (7, 'iPhone 17 Pro Max 256GB', '37990000', 'https://www.thegioididong.com/dtdd/iphone-17-pro-max', 'iOS 26', 'Apple A19 Pro 6 nhân', 'Hãng không công bố', 'Apple GPU 6 nhân', '12 GB', '256 GB', '241 GB', 'Không giới hạn', 'Chính 48 MP & Phụ 48 MP, 48 MP', 'HD 720p@30fps | FullHD 1080p@60fps | FullHD 1080p@30fps | FullHD 1080p@25fps | FullHD 1080p@120fps | 4K 2160p@60fps | 4K 2160p@30fps | 4K 2160p@25fps | 4K 2160p@24fps | 4K 2160p@120fps | 4K 2160p@100fps | 2.8K 60fps', 'Có', 'Ảnh Raw | Điều khiển camera (Camera Control) | Điều chỉnh khẩu độ | Zoom quang học | Zoom kỹ thuật số | Xóa phông | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Toàn cảnh (Panorama) | Smart HDR 5 | Siêu độ phân giải | Siêu cận (Macro) | Quay video định dạng Log | Quay video hiển thị kép | Quay video ProRes | Quay chậm (Slow Motion) | Live Photos | Gắn thẻ địa lý (Geotagging) | Góc siêu rộng (Ultrawide) | Dolby Vision HDR | Deep Fusion | Cinematic | Chụp ảnh liên tục | Chống rung điện tử kỹ thuật số (EIS) | Chống rung quang học (OIS) | Ban đêm (Night Mode) | Chế độ hành động (Action Mode) | Photonic Engine', '18 MP', 'Smart HDR 5 | Xóa phông | Video hiển thị kép | Tự động lấy nét (AF) | Trôi nhanh thời gian (Time Lapse) | Retina Flash | Quay video HD | Quay video Full HD | Quay video 4K | Quay chậm (Slow Motion) | Nhãn dán (AR Stickers) | Live Photos | Deep Fusion | Chụp ảnh Raw | Chụp đêm | Chống rung điện tử kỹ thuật số (EIS) | Cinematic | TrueDepth | Photonic Engine', 'OLED', 'Super Retina XDR (1320 x 2868 Pixels)', '6.9\" - Tần số quét120 Hz | 120 Hz', '3000 nits', 'Kính cường lực Ceramic Shield 2', '37 giờ', 'Li-Ion', '40 W', 'Tiết kiệm pin | Sạc pin nhanh | Sạc ngược qua cáp | Sạc không dây MagSafe | Sạc không dây', 'Mở khoá khuôn mặt Face ID', 'Âm thanh Dolby Atmos | Xoá vật thể AI | Viết AI | Trung tâm màn hình (Center Stage) | Phát hiện va chạm (Crash Detection) | Màn hình luôn hiển thị AOD | Khoanh tròn để tìm kiếm | HDR10+ | HDR10 | DCI-P3 | Công nghệ âm thanh Dolby Digital Plus | Công nghệ True Tone | Công nghệ HLG | Công nghê âm thanh Dolby Digital | Chạm 2 lần sáng màn hình | Apple Pay | Loa kép', 'IP68', 'Ghi âm mặc định | Ghi âm cuộc gọi', 'MP4 | AV1 | HEVC', 'MP3 | FLAC | Apple Lossless | APAC | AAC', 'Hỗ trợ 5G', '1 Nano SIM & 1 eSIM', 'Wi-Fi MIMO | Wi-Fi 7', 'iBeacon | QZSS | NavIC | GPS | GLONASS | GALILEO | BEIDOU', 'v6.0', 'Type-C', 'Type-C', 'NFC', 'Nguyên khối', 'Khung nhôm nguyên khối & Mặt lưng kính cường lực', 'Dài 163.4 mm - Ngang 78 mm - Dày 8.75 mm - Nặng 231 g', '09/2025', 'iPhone (Apple).Xem thông tin hãng | Xem thông tin hãng', '2025-11-04 21:51:37', 'tgdd_products_2025_11_04_21_51_36.xlsx');

SET FOREIGN_KEY_CHECKS = 1;
